package org.vorpal.kosmos.core

/**
 * Symbols used throughout Kosmos.
 * Collected here as [String] instances to make them easy to use and access.
 * Many more here: https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode
 */
object Symbols {
    const val APPROX = "≈"
    const val ARROW_UP = "↑"
    const val ARROW_DOWN = "↓"
    const val ASTERISK = "*"
    const val BB_A = "𝔸"
    const val BB_B = "𝔹"
    const val BB_C = "ℂ"
    const val BB_D = "𝔻"
    const val BB_E = "𝔼"
    const val BB_F = "𝔽"
    const val BB_G = "𝔾"
    const val BB_H = "ℍ"
    const val BB_I = "𝕀"
    const val BB_J = "𝕁"
    const val BB_K = "𝕂"
    const val BB_L = "𝕃"
    const val BB_M = "𝕄"
    const val BB_N = "ℕ"
    const val BB_O = "𝕆"
    const val BB_P = "ℙ"
    const val BB_Q = "ℚ"
    const val BB_R = "ℝ"
    const val BB_S = "𝕊"
    const val BB_T = "𝕋"
    const val BB_U = "𝕌"
    const val BB_V = "𝕍"
    const val BB_W = "𝕎"
    const val BB_X = "𝕏"
    const val BB_Y = "𝕐"
    const val BB_Z = "ℤ"
    const val BECAUSE = "∵"
    const val BOX = "□"
    const val COLON_EQUALS = "≔"
    const val DIAMOND = "⋄"
    const val DIAMOND_BIG = "◇"
    const val DIVISION = "÷"
    const val DOT = "·"
    const val DOTS_BACKSLASH = "⋱"
    const val DOTS_HORIZONTAL = "⋯"
    const val DOTS_SLASH = "⋰"
    const val DOTS_VERTICAL = "⋮"
    const val ENTAILS = "⊨"
    const val ENTAILS_NOT = "⊭"
    const val EQUALS_NOT = "≠"
    const val EXISTS = "∃"
    const val EXISTS_NOT = "∄"
    const val FALSE = "⊥"
    const val FORCES = "⊩"
    const val FORALL = "∀"
    const val IFF = "↔"
    const val IFF_BB = "⇔"
    const val IMPLIES = "→"
    const val IMPLIES_BB = "⇒"
    const val INFINITY = "∞"
    const val INTEGRAL = "∫"
    const val INTEGRAL_DOUBLE = "∬"
    const val INTEGRAL_TRIPLE = "∭"
    const val ISOMORPHIC = "≅"
    const val MAPS_INTO = "↪"
    const val MAPS_ONTO = "↠"
    const val MAPS_TO = "↦"
    const val MINUS = "-"
    const val MINUS_PLUS = "∓"
    const val NOT = "¬"
    const val NOTHING = ""
    const val O_DOT = "⊙"
    const val O_PLUS = "⊕"
    const val O_PLUS_BIG = "⨁"
    const val O_TIMES = "⊗"
    const val O_TIMES_BIG = "⨂"
    const val PLUS = "+"
    const val PLUSMINUS = "±"
    const val PROD = "∏"
    const val PROVES = "⊢"
    const val PROVES_NOT = "⊬"
    const val SET_ELEM = "∈"
    const val SET_ELEM_NOT = "∉"
    const val SET_EMPTY = "Ø"
    const val SET_INTERSECTION = "∩"
    const val SET_SUBSET = "⊂"
    const val SET_SUBSET_EQ = "⊆"
    const val SET_SUBSET_NOT = "⊄"
    const val SET_SUPERSET = "⊃"
    const val SET_SUPERSET_EQ = "⊇"
    const val SET_SUPERSET_NOT = "⊅"
    const val SET_SYMM_DIFF = "∆"
    const val SET_UNION = "∪"
    const val SET_UNION_DISJOINT = "⊔"
    const val SQRT = "√"
    const val SUM = "∑"
    const val THEREFORE = "∴"
    const val TIMES = "×"
    const val TRIANGLE_RIGHT = "⊳"
    const val TRIANGLE_LEFT = "⊲"
    const val TRIPLE_BARS = "≡"
    const val TRIPLE_BARS_NOT = "≢"
    const val TRUE = "⊤"
    const val VEE = "∨"
    const val WEDGE = "∧"

    // Aliases
    const val ARROW_RIGHT = IMPLIES
    const val INJECTION = MAPS_INTO
    const val RADICAL = SQRT
    const val SIGMA = SUM
    const val SURJECTION = MAPS_ONTO
    const val TURNSTYLE_DOUBLE = ENTAILS
    const val TURNSTYLE = PROVES

}
